version: "3"
services:
  influxdb:
    image: "influxdb:1.6.6"
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    volumes:
      - ./influxdb:/var/lib/influxdb
  garie-lighthouse:
    image: "garie/lighthouse"
    ports:
      - 3000:3000
    environment:
      - HOST=influxdb
    volumes:
      - ./garie-config.json:/usr/src/garie-lighthouse/config.json
      - ./plugins/garie-lighthouse/reports:/usr/src/garie-lighthouse/reports
      - ./plugins/garie-lighthouse/logs:/usr/src/garie-lighthouse/logs
    depends_on:
      - influxdb
 # garie-browsertime:
   
  grafana:
    image: grafana/grafana
    ports:
      - 80:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
    volumes:
      - "./grafana_data:/var/lib/grafana"
      - "./config/grafana/provisioning:/etc/grafana/provisioning"
      - "./config/grafana/grafana.ini:/etc/grafana/grafana.ini"
    depends_on:
      - influxdb
    user: ${CURRENT_UID}
  chronograf:
    image: "chronograf:latest"
    ports:
      - 8888:8888
    depends_on:
      - influxdb
